name: deploy-manifests

on:
  push:
    branches:
      - main
    paths:
      - "infra/**"

env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  GKE_CLUSTER: autopilot-cluster-1
  GKE_ZONE: us-central1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Authentication
      - uses: google-github-actions/auth@v0.1
        with:
          credentials: ${{ secrets.GKE_SA_KEY }}

      # Setup gcloud CLI
      - uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          version: 'latest'
          skip_install: true

      # Authenticate with GKE and get the credentials for your cluster
      - run: gcloud container clusters get-credentials $GKE_CLUSTER --zone=$GKE_ZONE

      # Apply the Kubernetes manifests
      - run: kubectl apply -f infra/k8s && kubectl apply -f infra/k8s-prod
