name: deploy-manifests

on:
  push:
    branches:
      - main
    paths:
      - "infra/**"

env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  GKE_CLUSTER: autopilot-cluster-1
  GKE_ZONE: us-central1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Setup gcloud CLI
      - uses: google-github-actions/setup-gcloud@1bee7de035d65ec5da40a31f8589e240eba8fde5
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.PROJECT_ID }}

      # Authenticate with GKE and get the credentials for your cluster
      - run: gcloud container clusters get-credentials $GKE_CLUSTER --zone=$GKE_ZONE

      # Apply the Kubernetes manifests
      - run: kubectl apply -f infra/k8s && kubectl apply -f infra/k8s-prod
